name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  main:
    name: Build 🏗️
    uses: ./.github/workflows/__package.yml
    with:
      commit: ${{ github.sha }}
      commit: ${{ github.sha }}
      workflow_run_id: ${{ github.run_id }}
      comment: false
